In [3]:
A <- c(1,2,3)
B <- c(4,5,6)
mat <- rbind(A,B)
mat

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

In [6]:
mat <- matrix(1:9,nrow = 3)
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [8]:
is.matrix(mat)

[1] TRUE

In [11]:
mat2 <- matrix(1:25,byrow=T,nrow=5)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [13]:
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

In [14]:
sum(mat2)

[1] 325

In [15]:
help(runif)

In [17]:
matrix(runif(20,min=0,max=100), nrow= 4)

[,1]      [,2]     [,3]      [,4]      [,5]     
[1,]  0.239726 21.90648  6.086832 90.262886 33.185538
[2,] 25.658961 62.05598 95.561480 24.135900 19.498668
[3,] 23.113572 82.40718 34.599039  1.745421  5.743024
[4,] 39.322780 35.60893 26.053233 74.646229 89.384867